// Auto-generated by scripts/remove-comparison-sections.mjs — do not edit manually.
import type { Lesson } from "../catalog";

export const domLessons: Lesson[] = [
  {
    "slug": "Brauzernoe-okruzhenie",
    "track": "dom",
    "order": 1,
    "title": "Браузерное окружение, спецификации",
    "summary": "Pонять структуру браузерного окружения: window, document, navigator, и как спецификации влияют на доступные API.",
    "sourceTitle": "Урок 1.1. Браузерное окружение, спецификации",
    "blocks": [
      {
        "type": "heading",
        "text": "Браузерное окружение, спецификации"
      },
      {
        "type": "heading",
        "text": "Цель урока"
      },
      {
        "type": "p",
        "text": "Pонять структуру браузерного окружения: window, document, navigator, и как спецификации (W3C, WHATWG, TC39) влияют на доступные API."
      },
      {
        "type": "heading",
        "text": "Теория"
      },
      {
        "type": "heading",
        "text": "Ментальная модель"
      },
      {
        "type": "p",
        "text": "Браузерное окружение, спецификации — важная тема для понимания работы с DOM в браузере. Каждый элемент страницы — это объект со свойствами и методами, которые можно изучить и использовать для создания интерактивных веб-страниц."
      },
      {
        "type": "heading",
        "text": "Основные концепции"
      },
      {
        "type": "p",
        "text": "1. Структура: DOM — это дерево узлов, где каждый элемент имеет родителя и детей"
      },
      {
        "type": "p",
        "text": "2. События: Пользовательские действия генерируют события, которые можно перехватывать"
      },
      {
        "type": "p",
        "text": "3. Манипуляции: Создание, изменение и удаление элементов для динамического контента"
      },
      {
        "type": "p",
        "text": "4. Производительность: Правильная работа с DOM критична для быстродействия"
      },
      {
        "type": "heading",
        "text": "Примеры кода"
      },
      {
        "type": "heading",
        "text": "Базовый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "let element = document.querySelector(\".example\");\nconsole.log(element);"
      },
      {
        "type": "heading",
        "text": "Продвинутый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "class DOMHelper {\n  static createElement(tag, attrs, children) {\n    let el = document.createElement(tag);\n    if (attrs) {\n      Object.entries(attrs).forEach(function([k, v]) {\n        el.setAttribute(k, v);\n      });\n    }\n    if (children) {\n      children.forEach(function(child) { el.appendChild(child); });\n    }\n    return el;\n  }\n  \n  static removeElement(el) {\n    if (el && el.remove) el.remove();\n  }\n}"
      },
      {
        "type": "heading",
        "text": "Подводные камни"
      },
      {
        "type": "list",
        "items": [
          "Производительность DOM: Каждое изменение DOM вызывает перерисовку (reflow/repaint)",
          "Пакетные обновления: Используйте DocumentFragment для пакетной вставки",
          "Event listeners: Не забывайте снимать обработчики при удалении элементов",
          "CSSOM vs DOM: Стили и разметка — отдельные деревья при рендеринге",
          "requestAnimationFrame: Используйте для анимаций вместо setTimeout"
        ]
      },
      {
        "type": "heading",
        "text": "Практические задания"
      },
      {
        "type": "heading",
        "text": "Базовый уровень"
      },
      {
        "type": "p",
        "text": "1. Найдите элемент по CSS-селектору и измените его текст."
      },
      {
        "type": "p",
        "text": "2. Создайте новый DOM-элемент и добавьте его на страницу."
      },
      {
        "type": "p",
        "text": "3. Удалите элемент из DOM-дерева."
      },
      {
        "type": "heading",
        "text": "Средний уровень"
      },
      {
        "type": "p",
        "text": "1. Реализуйте функцию пакетного обновления DOM."
      },
      {
        "type": "p",
        "text": "2. Создайте динамический список с добавлением и удалением элементов."
      },
      {
        "type": "p",
        "text": "3. Реализуйте валидацию формы в реальном времени."
      },
      {
        "type": "heading",
        "text": "Хардкор"
      },
      {
        "type": "p",
        "text": "1. Создайте простой virtual DOM с диффингом."
      },
      {
        "type": "p",
        "text": "2. Реализуйте систему делегирования событий с поддержкой вложенных селекторов."
      },
      {
        "type": "p",
        "text": "3. Напишите компонент-рендерер с минимальным влиянием на рефлоу."
      },
      {
        "type": "heading",
        "text": "Итог"
      },
      {
        "type": "p",
        "text": "Браузерное окружение, спецификации — фундаментальная тема для работы с веб-страницами. Понимание основных концепций и лучших практик поможет создавать быстрые и интерактивные приложения. Всегда думайте о производительности при манипуляциях с DOM."
      }
    ]
  },
  {
    "slug": "dom-derevo-uglublenno",
    "track": "dom",
    "order": 2,
    "title": "DOM-дерево (углублённо)",
    "summary": "Глубоко изучить структуру DOM: узлы, типы узлов, NodeList, HTMLCollection.",
    "sourceTitle": "Урок 1.2. DOM-дерево (углублённо)",
    "blocks": [
      {
        "type": "heading",
        "text": "DOM-дерево (углублённо)"
      },
      {
        "type": "heading",
        "text": "Цель урока"
      },
      {
        "type": "p",
        "text": "Глубоко изучить структуру DOM: узлы, типы узлов, NodeList, HTMLCollection, и разницу между ними."
      },
      {
        "type": "heading",
        "text": "Теория"
      },
      {
        "type": "heading",
        "text": "Ментальная модель"
      },
      {
        "type": "p",
        "text": "DOM-дерево (углублённо) — важная тема для понимания работы с DOM в браузере. Каждый элемент страницы — это объект со свойствами и методами, которые можно изучить и использовать для создания интерактивных веб-страниц."
      },
      {
        "type": "heading",
        "text": "Основные концепции"
      },
      {
        "type": "p",
        "text": "1. Структура: DOM — это дерево узлов, где каждый элемент имеет родителя и детей"
      },
      {
        "type": "p",
        "text": "2. События: Пользовательские действия генерируют события, которые можно перехватывать"
      },
      {
        "type": "p",
        "text": "3. Манипуляции: Создание, изменение и удаление элементов для динамического контента"
      },
      {
        "type": "p",
        "text": "4. Производительность: Правильная работа с DOM критична для быстродействия"
      },
      {
        "type": "heading",
        "text": "Примеры кода"
      },
      {
        "type": "heading",
        "text": "Базовый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "let element = document.querySelector(\".example\");\nconsole.log(element);"
      },
      {
        "type": "heading",
        "text": "Продвинутый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "class DOMHelper {\n  static createElement(tag, attrs, children) {\n    let el = document.createElement(tag);\n    if (attrs) {\n      Object.entries(attrs).forEach(function([k, v]) {\n        el.setAttribute(k, v);\n      });\n    }\n    if (children) {\n      children.forEach(function(child) { el.appendChild(child); });\n    }\n    return el;\n  }\n  \n  static removeElement(el) {\n    if (el && el.remove) el.remove();\n  }\n}"
      },
      {
        "type": "heading",
        "text": "Подводные камни"
      },
      {
        "type": "list",
        "items": [
          "Производительность DOM: Каждое изменение DOM вызывает перерисовку (reflow/repaint)",
          "Пакетные обновления: Используйте DocumentFragment для пакетной вставки",
          "Event listeners: Не забывайте снимать обработчики при удалении элементов",
          "CSSOM vs DOM: Стили и разметка — отдельные деревья при рендеринге",
          "requestAnimationFrame: Используйте для анимаций вместо setTimeout"
        ]
      },
      {
        "type": "heading",
        "text": "Практические задания"
      },
      {
        "type": "heading",
        "text": "Базовый уровень"
      },
      {
        "type": "p",
        "text": "1. Найдите элемент по CSS-селектору и измените его текст."
      },
      {
        "type": "p",
        "text": "2. Создайте новый DOM-элемент и добавьте его на страницу."
      },
      {
        "type": "p",
        "text": "3. Удалите элемент из DOM-дерева."
      },
      {
        "type": "heading",
        "text": "Средний уровень"
      },
      {
        "type": "p",
        "text": "1. Реализуйте функцию пакетного обновления DOM."
      },
      {
        "type": "p",
        "text": "2. Создайте динамический список с добавлением и удалением элементов."
      },
      {
        "type": "p",
        "text": "3. Реализуйте валидацию формы в реальном времени."
      },
      {
        "type": "heading",
        "text": "Хардкор"
      },
      {
        "type": "p",
        "text": "1. Создайте простой virtual DOM с диффингом."
      },
      {
        "type": "p",
        "text": "2. Реализуйте систему делегирования событий с поддержкой вложенных селекторов."
      },
      {
        "type": "p",
        "text": "3. Напишите компонент-рендерер с минимальным влиянием на рефлоу."
      },
      {
        "type": "heading",
        "text": "Итог"
      },
      {
        "type": "p",
        "text": "DOM-дерево (углублённо) — фундаментальная тема для работы с веб-страницами. Понимание основных концепций и лучших практик поможет создавать быстрые и интерактивные приложения. Всегда думайте о производительности при манипуляциях с DOM."
      }
    ]
  },
  {
    "slug": "navigatsiya-po-dom-elementam",
    "track": "dom",
    "order": 3,
    "title": "Навигация по DOM-элементам",
    "summary": "Научиться перемещаться по DOM-дереву через childNodes, children, parentNode, siblings.",
    "sourceTitle": "Урок 1.3. Навигация по DOM-элементам",
    "blocks": [
      {
        "type": "heading",
        "text": "Навигация по DOM-элементам"
      },
      {
        "type": "heading",
        "text": "Цель урока"
      },
      {
        "type": "p",
        "text": "Научиться перемещаться по DOM-дереву через childNodes, children, parentNode, siblings и другие свойства навигации."
      },
      {
        "type": "heading",
        "text": "Теория"
      },
      {
        "type": "heading",
        "text": "Ментальная модель"
      },
      {
        "type": "p",
        "text": "Навигация по DOM-элементам — важная тема для понимания работы с DOM в браузере. Каждый элемент страницы — это объект со свойствами и методами, которые можно изучить и использовать для создания интерактивных веб-страниц."
      },
      {
        "type": "heading",
        "text": "Основные концепции"
      },
      {
        "type": "p",
        "text": "1. Структура: DOM — это дерево узлов, где каждый элемент имеет родителя и детей"
      },
      {
        "type": "p",
        "text": "2. События: Пользовательские действия генерируют события, которые можно перехватывать"
      },
      {
        "type": "p",
        "text": "3. Манипуляции: Создание, изменение и удаление элементов для динамического контента"
      },
      {
        "type": "p",
        "text": "4. Производительность: Правильная работа с DOM критична для быстродействия"
      },
      {
        "type": "heading",
        "text": "Примеры кода"
      },
      {
        "type": "heading",
        "text": "Базовый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "let element = document.querySelector(\".example\");\nconsole.log(element);"
      },
      {
        "type": "heading",
        "text": "Продвинутый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "class DOMHelper {\n  static createElement(tag, attrs, children) {\n    let el = document.createElement(tag);\n    if (attrs) {\n      Object.entries(attrs).forEach(function([k, v]) {\n        el.setAttribute(k, v);\n      });\n    }\n    if (children) {\n      children.forEach(function(child) { el.appendChild(child); });\n    }\n    return el;\n  }\n  \n  static removeElement(el) {\n    if (el && el.remove) el.remove();\n  }\n}"
      },
      {
        "type": "heading",
        "text": "Подводные камни"
      },
      {
        "type": "list",
        "items": [
          "Производительность DOM: Каждое изменение DOM вызывает перерисовку (reflow/repaint)",
          "Пакетные обновления: Используйте DocumentFragment для пакетной вставки",
          "Event listeners: Не забывайте снимать обработчики при удалении элементов",
          "CSSOM vs DOM: Стили и разметка — отдельные деревья при рендеринге",
          "requestAnimationFrame: Используйте для анимаций вместо setTimeout"
        ]
      },
      {
        "type": "heading",
        "text": "Практические задания"
      },
      {
        "type": "heading",
        "text": "Базовый уровень"
      },
      {
        "type": "p",
        "text": "1. Найдите элемент по CSS-селектору и измените его текст."
      },
      {
        "type": "p",
        "text": "2. Создайте новый DOM-элемент и добавьте его на страницу."
      },
      {
        "type": "p",
        "text": "3. Удалите элемент из DOM-дерева."
      },
      {
        "type": "heading",
        "text": "Средний уровень"
      },
      {
        "type": "p",
        "text": "1. Реализуйте функцию пакетного обновления DOM."
      },
      {
        "type": "p",
        "text": "2. Создайте динамический список с добавлением и удалением элементов."
      },
      {
        "type": "p",
        "text": "3. Реализуйте валидацию формы в реальном времени."
      },
      {
        "type": "heading",
        "text": "Хардкор"
      },
      {
        "type": "p",
        "text": "1. Создайте простой virtual DOM с диффингом."
      },
      {
        "type": "p",
        "text": "2. Реализуйте систему делегирования событий с поддержкой вложенных селекторов."
      },
      {
        "type": "p",
        "text": "3. Напишите компонент-рендерер с минимальным влиянием на рефлоу."
      },
      {
        "type": "heading",
        "text": "Итог"
      },
      {
        "type": "p",
        "text": "Навигация по DOM-элементам — фундаментальная тема для работы с веб-страницами. Понимание основных концепций и лучших практик поможет создавать быстрые и интерактивные приложения. Всегда думайте о производительности при манипуляциях с DOM."
      }
    ]
  },
  {
    "slug": "svojstva-uzlov-tip-tag-soderzhimoe",
    "track": "dom",
    "order": 4,
    "title": "Свойства узлов: тип, тег, содержимое",
    "summary": "Понять разницу между nodeType, nodeName, tagName, innerHTML, textContent.",
    "sourceTitle": "Урок 1.4. Свойства узлов: тип, тег, содержимое",
    "blocks": [
      {
        "type": "heading",
        "text": "Свойства узлов: тип, тег, содержимое"
      },
      {
        "type": "heading",
        "text": "Цель урока"
      },
      {
        "type": "p",
        "text": "Понять разницу между nodeType, nodeName, tagName, innerHTML, textContent и когда использовать каждое."
      },
      {
        "type": "heading",
        "text": "Теория"
      },
      {
        "type": "heading",
        "text": "Ментальная модель"
      },
      {
        "type": "p",
        "text": "Свойства узлов: тип, тег, содержимое — важная тема для понимания работы с DOM в браузере. Каждый элемент страницы — это объект со свойствами и методами, которые можно изучить и использовать для создания интерактивных веб-страниц."
      },
      {
        "type": "heading",
        "text": "Основные концепции"
      },
      {
        "type": "p",
        "text": "1. Структура: DOM — это дерево узлов, где каждый элемент имеет родителя и детей"
      },
      {
        "type": "p",
        "text": "2. События: Пользовательские действия генерируют события, которые можно перехватывать"
      },
      {
        "type": "p",
        "text": "3. Манипуляции: Создание, изменение и удаление элементов для динамического контента"
      },
      {
        "type": "p",
        "text": "4. Производительность: Правильная работа с DOM критична для быстродействия"
      },
      {
        "type": "heading",
        "text": "Примеры кода"
      },
      {
        "type": "heading",
        "text": "Базовый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "let element = document.querySelector(\".example\");\nconsole.log(element);"
      },
      {
        "type": "heading",
        "text": "Продвинутый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "class DOMHelper {\n  static createElement(tag, attrs, children) {\n    let el = document.createElement(tag);\n    if (attrs) {\n      Object.entries(attrs).forEach(function([k, v]) {\n        el.setAttribute(k, v);\n      });\n    }\n    if (children) {\n      children.forEach(function(child) { el.appendChild(child); });\n    }\n    return el;\n  }\n  \n  static removeElement(el) {\n    if (el && el.remove) el.remove();\n  }\n}"
      },
      {
        "type": "heading",
        "text": "Подводные камни"
      },
      {
        "type": "list",
        "items": [
          "Производительность DOM: Каждое изменение DOM вызывает перерисовку (reflow/repaint)",
          "Пакетные обновления: Используйте DocumentFragment для пакетной вставки",
          "Event listeners: Не забывайте снимать обработчики при удалении элементов",
          "CSSOM vs DOM: Стили и разметка — отдельные деревья при рендеринге",
          "requestAnimationFrame: Используйте для анимаций вместо setTimeout"
        ]
      },
      {
        "type": "heading",
        "text": "Практические задания"
      },
      {
        "type": "heading",
        "text": "Базовый уровень"
      },
      {
        "type": "p",
        "text": "1. Найдите элемент по CSS-селектору и измените его текст."
      },
      {
        "type": "p",
        "text": "2. Создайте новый DOM-элемент и добавьте его на страницу."
      },
      {
        "type": "p",
        "text": "3. Удалите элемент из DOM-дерева."
      },
      {
        "type": "heading",
        "text": "Средний уровень"
      },
      {
        "type": "p",
        "text": "1. Реализуйте функцию пакетного обновления DOM."
      },
      {
        "type": "p",
        "text": "2. Создайте динамический список с добавлением и удалением элементов."
      },
      {
        "type": "p",
        "text": "3. Реализуйте валидацию формы в реальном времени."
      },
      {
        "type": "heading",
        "text": "Хардкор"
      },
      {
        "type": "p",
        "text": "1. Создайте простой virtual DOM с диффингом."
      },
      {
        "type": "p",
        "text": "2. Реализуйте систему делегирования событий с поддержкой вложенных селекторов."
      },
      {
        "type": "p",
        "text": "3. Напишите компонент-рендерер с минимальным влиянием на рефлоу."
      },
      {
        "type": "heading",
        "text": "Итог"
      },
      {
        "type": "p",
        "text": "Свойства узлов: тип, тег, содержимое — фундаментальная тема для работы с веб-страницами. Понимание основных концепций и лучших практик поможет создавать быстрые и интерактивные приложения. Всегда думайте о производительности при манипуляциях с DOM."
      }
    ]
  },
  {
    "slug": "atributy-i-svojstva",
    "track": "dom",
    "order": 5,
    "title": "Атрибуты и свойства",
    "summary": "Различать HTML-атрибуты и DOM-свойства, понять когда что использовать.",
    "sourceTitle": "Урок 1.5. Атрибуты и свойства",
    "blocks": [
      {
        "type": "heading",
        "text": "Атрибуты и свойства"
      },
      {
        "type": "heading",
        "text": "Цель урока"
      },
      {
        "type": "p",
        "text": "Различать HTML-атрибуты (getAttribute/setAttribute) и DOM-свойства (elem.name), понять когда что использовать."
      },
      {
        "type": "heading",
        "text": "Теория"
      },
      {
        "type": "heading",
        "text": "Ментальная модель"
      },
      {
        "type": "p",
        "text": "Атрибуты и свойства — важная тема для понимания работы с DOM в браузере. Каждый элемент страницы — это объект со свойствами и методами, которые можно изучить и использовать для создания интерактивных веб-страниц."
      },
      {
        "type": "heading",
        "text": "Основные концепции"
      },
      {
        "type": "p",
        "text": "1. Структура: DOM — это дерево узлов, где каждый элемент имеет родителя и детей"
      },
      {
        "type": "p",
        "text": "2. События: Пользовательские действия генерируют события, которые можно перехватывать"
      },
      {
        "type": "p",
        "text": "3. Манипуляции: Создание, изменение и удаление элементов для динамического контента"
      },
      {
        "type": "p",
        "text": "4. Производительность: Правильная работа с DOM критична для быстродействия"
      },
      {
        "type": "heading",
        "text": "Примеры кода"
      },
      {
        "type": "heading",
        "text": "Базовый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "let element = document.querySelector(\".example\");\nconsole.log(element);"
      },
      {
        "type": "heading",
        "text": "Продвинутый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "class DOMHelper {\n  static createElement(tag, attrs, children) {\n    let el = document.createElement(tag);\n    if (attrs) {\n      Object.entries(attrs).forEach(function([k, v]) {\n        el.setAttribute(k, v);\n      });\n    }\n    if (children) {\n      children.forEach(function(child) { el.appendChild(child); });\n    }\n    return el;\n  }\n  \n  static removeElement(el) {\n    if (el && el.remove) el.remove();\n  }\n}"
      },
      {
        "type": "heading",
        "text": "Подводные камни"
      },
      {
        "type": "list",
        "items": [
          "Производительность DOM: Каждое изменение DOM вызывает перерисовку (reflow/repaint)",
          "Пакетные обновления: Используйте DocumentFragment для пакетной вставки",
          "Event listeners: Не забывайте снимать обработчики при удалении элементов",
          "CSSOM vs DOM: Стили и разметка — отдельные деревья при рендеринге",
          "requestAnimationFrame: Используйте для анимаций вместо setTimeout"
        ]
      },
      {
        "type": "heading",
        "text": "Практические задания"
      },
      {
        "type": "heading",
        "text": "Базовый уровень"
      },
      {
        "type": "p",
        "text": "1. Найдите элемент по CSS-селектору и измените его текст."
      },
      {
        "type": "p",
        "text": "2. Создайте новый DOM-элемент и добавьте его на страницу."
      },
      {
        "type": "p",
        "text": "3. Удалите элемент из DOM-дерева."
      },
      {
        "type": "heading",
        "text": "Средний уровень"
      },
      {
        "type": "p",
        "text": "1. Реализуйте функцию пакетного обновления DOM."
      },
      {
        "type": "p",
        "text": "2. Создайте динамический список с добавлением и удалением элементов."
      },
      {
        "type": "p",
        "text": "3. Реализуйте валидацию формы в реальном времени."
      },
      {
        "type": "heading",
        "text": "Хардкор"
      },
      {
        "type": "p",
        "text": "1. Создайте простой virtual DOM с диффингом."
      },
      {
        "type": "p",
        "text": "2. Реализуйте систему делегирования событий с поддержкой вложенных селекторов."
      },
      {
        "type": "p",
        "text": "3. Напишите компонент-рендерер с минимальным влиянием на рефлоу."
      },
      {
        "type": "heading",
        "text": "Итог"
      },
      {
        "type": "p",
        "text": "Атрибуты и свойства — фундаментальная тема для работы с веб-страницами. Понимание основных концепций и лучших практик поможет создавать быстрые и интерактивные приложения. Всегда думайте о производительности при манипуляциях с DOM."
      }
    ]
  },
  {
    "slug": "izmenenie-dokumenta-sozdanie-vstavka-udalenie",
    "track": "dom",
    "order": 6,
    "title": "Изменение документа (создание, вставка, удаление)",
    "summary": "Научиться создавать, вставлять и удалять DOM-узлы.",
    "sourceTitle": "Урок 2.1. Изменение документа (создание, вставка, удаление)",
    "blocks": [
      {
        "type": "heading",
        "text": "Изменение документа (создание, вставка, удаление)"
      },
      {
        "type": "heading",
        "text": "Цель урока"
      },
      {
        "type": "p",
        "text": "Научиться создавать, вставлять и удалять DOM-узлы: createElement, append, insertBefore, remove."
      },
      {
        "type": "heading",
        "text": "Теория"
      },
      {
        "type": "heading",
        "text": "Ментальная модель"
      },
      {
        "type": "p",
        "text": "Изменение документа (создание, вставка, удаление) — важная тема для понимания работы с DOM в браузере. Каждый элемент страницы — это объект со свойствами и методами, которые можно изучить и использовать для создания интерактивных веб-страниц."
      },
      {
        "type": "heading",
        "text": "Основные концепции"
      },
      {
        "type": "p",
        "text": "1. Структура: DOM — это дерево узлов, где каждый элемент имеет родителя и детей"
      },
      {
        "type": "p",
        "text": "2. События: Пользовательские действия генерируют события, которые можно перехватывать"
      },
      {
        "type": "p",
        "text": "3. Манипуляции: Создание, изменение и удаление элементов для динамического контента"
      },
      {
        "type": "p",
        "text": "4. Производительность: Правильная работа с DOM критична для быстродействия"
      },
      {
        "type": "heading",
        "text": "Примеры кода"
      },
      {
        "type": "heading",
        "text": "Базовый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "let element = document.querySelector(\".example\");\nconsole.log(element);"
      },
      {
        "type": "heading",
        "text": "Продвинутый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "class DOMHelper {\n  static createElement(tag, attrs, children) {\n    let el = document.createElement(tag);\n    if (attrs) {\n      Object.entries(attrs).forEach(function([k, v]) {\n        el.setAttribute(k, v);\n      });\n    }\n    if (children) {\n      children.forEach(function(child) { el.appendChild(child); });\n    }\n    return el;\n  }\n  \n  static removeElement(el) {\n    if (el && el.remove) el.remove();\n  }\n}"
      },
      {
        "type": "heading",
        "text": "Подводные камни"
      },
      {
        "type": "list",
        "items": [
          "Производительность DOM: Каждое изменение DOM вызывает перерисовку (reflow/repaint)",
          "Пакетные обновления: Используйте DocumentFragment для пакетной вставки",
          "Event listeners: Не забывайте снимать обработчики при удалении элементов",
          "CSSOM vs DOM: Стили и разметка — отдельные деревья при рендеринге",
          "requestAnimationFrame: Используйте для анимаций вместо setTimeout"
        ]
      },
      {
        "type": "heading",
        "text": "Практические задания"
      },
      {
        "type": "heading",
        "text": "Базовый уровень"
      },
      {
        "type": "p",
        "text": "1. Найдите элемент по CSS-селектору и измените его текст."
      },
      {
        "type": "p",
        "text": "2. Создайте новый DOM-элемент и добавьте его на страницу."
      },
      {
        "type": "p",
        "text": "3. Удалите элемент из DOM-дерева."
      },
      {
        "type": "heading",
        "text": "Средний уровень"
      },
      {
        "type": "p",
        "text": "1. Реализуйте функцию пакетного обновления DOM."
      },
      {
        "type": "p",
        "text": "2. Создайте динамический список с добавлением и удалением элементов."
      },
      {
        "type": "p",
        "text": "3. Реализуйте валидацию формы в реальном времени."
      },
      {
        "type": "heading",
        "text": "Хардкор"
      },
      {
        "type": "p",
        "text": "1. Создайте простой virtual DOM с диффингом."
      },
      {
        "type": "p",
        "text": "2. Реализуйте систему делегирования событий с поддержкой вложенных селекторов."
      },
      {
        "type": "p",
        "text": "3. Напишите компонент-рендерер с минимальным влиянием на рефлоу."
      },
      {
        "type": "heading",
        "text": "Итог"
      },
      {
        "type": "p",
        "text": "Изменение документа (создание, вставка, удаление) — фундаментальная тема для работы с веб-страницами. Понимание основных концепций и лучших практик поможет создавать быстрые и интерактивные приложения. Всегда думайте о производительности при манипуляциях с DOM."
      }
    ]
  },
  {
    "slug": "stili-i-klassy",
    "track": "dom",
    "order": 7,
    "title": "Стили и классы",
    "summary": "Управлять стилями через style, classList, getComputedStyle.",
    "sourceTitle": "Урок 2.2. Стили и классы",
    "blocks": [
      {
        "type": "heading",
        "text": "Стили и классы"
      },
      {
        "type": "heading",
        "text": "Цель урока"
      },
      {
        "type": "p",
        "text": "Управлять стилями через style, classList, getComputedStyle и понять разницу между инлайн-стилями и CSS-классами."
      },
      {
        "type": "heading",
        "text": "Теория"
      },
      {
        "type": "heading",
        "text": "Ментальная модель"
      },
      {
        "type": "p",
        "text": "Стили и классы — важная тема для понимания работы с DOM в браузере. Каждый элемент страницы — это объект со свойствами и методами, которые можно изучить и использовать для создания интерактивных веб-страниц."
      },
      {
        "type": "heading",
        "text": "Основные концепции"
      },
      {
        "type": "p",
        "text": "1. Структура: DOM — это дерево узлов, где каждый элемент имеет родителя и детей"
      },
      {
        "type": "p",
        "text": "2. События: Пользовательские действия генерируют события, которые можно перехватывать"
      },
      {
        "type": "p",
        "text": "3. Манипуляции: Создание, изменение и удаление элементов для динамического контента"
      },
      {
        "type": "p",
        "text": "4. Производительность: Правильная работа с DOM критична для быстродействия"
      },
      {
        "type": "heading",
        "text": "Примеры кода"
      },
      {
        "type": "heading",
        "text": "Базовый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "let element = document.querySelector(\".example\");\nconsole.log(element);"
      },
      {
        "type": "heading",
        "text": "Продвинутый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "class DOMHelper {\n  static createElement(tag, attrs, children) {\n    let el = document.createElement(tag);\n    if (attrs) {\n      Object.entries(attrs).forEach(function([k, v]) {\n        el.setAttribute(k, v);\n      });\n    }\n    if (children) {\n      children.forEach(function(child) { el.appendChild(child); });\n    }\n    return el;\n  }\n  \n  static removeElement(el) {\n    if (el && el.remove) el.remove();\n  }\n}"
      },
      {
        "type": "heading",
        "text": "Подводные камни"
      },
      {
        "type": "list",
        "items": [
          "Производительность DOM: Каждое изменение DOM вызывает перерисовку (reflow/repaint)",
          "Пакетные обновления: Используйте DocumentFragment для пакетной вставки",
          "Event listeners: Не забывайте снимать обработчики при удалении элементов",
          "CSSOM vs DOM: Стили и разметка — отдельные деревья при рендеринге",
          "requestAnimationFrame: Используйте для анимаций вместо setTimeout"
        ]
      },
      {
        "type": "heading",
        "text": "Практические задания"
      },
      {
        "type": "heading",
        "text": "Базовый уровень"
      },
      {
        "type": "p",
        "text": "1. Найдите элемент по CSS-селектору и измените его текст."
      },
      {
        "type": "p",
        "text": "2. Создайте новый DOM-элемент и добавьте его на страницу."
      },
      {
        "type": "p",
        "text": "3. Удалите элемент из DOM-дерева."
      },
      {
        "type": "heading",
        "text": "Средний уровень"
      },
      {
        "type": "p",
        "text": "1. Реализуйте функцию пакетного обновления DOM."
      },
      {
        "type": "p",
        "text": "2. Создайте динамический список с добавлением и удалением элементов."
      },
      {
        "type": "p",
        "text": "3. Реализуйте валидацию формы в реальном времени."
      },
      {
        "type": "heading",
        "text": "Хардкор"
      },
      {
        "type": "p",
        "text": "1. Создайте простой virtual DOM с диффингом."
      },
      {
        "type": "p",
        "text": "2. Реализуйте систему делегирования событий с поддержкой вложенных селекторов."
      },
      {
        "type": "p",
        "text": "3. Напишите компонент-рендерер с минимальным влиянием на рефлоу."
      },
      {
        "type": "heading",
        "text": "Итог"
      },
      {
        "type": "p",
        "text": "Стили и классы — фундаментальная тема для работы с веб-страницами. Понимание основных концепций и лучших практик поможет создавать быстрые и интерактивные приложения. Всегда думайте о производительности при манипуляциях с DOM."
      }
    ]
  },
  {
    "slug": "razmery-i-prokrutka-elementov",
    "track": "dom",
    "order": 8,
    "title": "Размеры и прокрутка элементов",
    "summary": "Измерять элементы: offsetWidth, clientWidth, scrollWidth.",
    "sourceTitle": "Урок 2.3. Размеры и прокрутка элементов",
    "blocks": [
      {
        "type": "heading",
        "text": "Размеры и прокрутка элементов"
      },
      {
        "type": "heading",
        "text": "Цель урока"
      },
      {
        "type": "p",
        "text": "Измерять элементы: offsetWidth, clientWidth, scrollWidth, и управлять прокруткой: scrollTop, scrollLeft."
      },
      {
        "type": "heading",
        "text": "Теория"
      },
      {
        "type": "heading",
        "text": "Ментальная модель"
      },
      {
        "type": "p",
        "text": "Размеры и прокрутка элементов — важная тема для понимания работы с DOM в браузере. Каждый элемент страницы — это объект со свойствами и методами, которые можно изучить и использовать для создания интерактивных веб-страниц."
      },
      {
        "type": "heading",
        "text": "Основные концепции"
      },
      {
        "type": "p",
        "text": "1. Структура: DOM — это дерево узлов, где каждый элемент имеет родителя и детей"
      },
      {
        "type": "p",
        "text": "2. События: Пользовательские действия генерируют события, которые можно перехватывать"
      },
      {
        "type": "p",
        "text": "3. Манипуляции: Создание, изменение и удаление элементов для динамического контента"
      },
      {
        "type": "p",
        "text": "4. Производительность: Правильная работа с DOM критична для быстродействия"
      },
      {
        "type": "heading",
        "text": "Примеры кода"
      },
      {
        "type": "heading",
        "text": "Базовый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "let element = document.querySelector(\".example\");\nconsole.log(element);"
      },
      {
        "type": "heading",
        "text": "Продвинутый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "class DOMHelper {\n  static createElement(tag, attrs, children) {\n    let el = document.createElement(tag);\n    if (attrs) {\n      Object.entries(attrs).forEach(function([k, v]) {\n        el.setAttribute(k, v);\n      });\n    }\n    if (children) {\n      children.forEach(function(child) { el.appendChild(child); });\n    }\n    return el;\n  }\n  \n  static removeElement(el) {\n    if (el && el.remove) el.remove();\n  }\n}"
      },
      {
        "type": "heading",
        "text": "Подводные камни"
      },
      {
        "type": "list",
        "items": [
          "Производительность DOM: Каждое изменение DOM вызывает перерисовку (reflow/repaint)",
          "Пакетные обновления: Используйте DocumentFragment для пакетной вставки",
          "Event listeners: Не забывайте снимать обработчики при удалении элементов",
          "CSSOM vs DOM: Стили и разметка — отдельные деревья при рендеринге",
          "requestAnimationFrame: Используйте для анимаций вместо setTimeout"
        ]
      },
      {
        "type": "heading",
        "text": "Практические задания"
      },
      {
        "type": "heading",
        "text": "Базовый уровень"
      },
      {
        "type": "p",
        "text": "1. Найдите элемент по CSS-селектору и измените его текст."
      },
      {
        "type": "p",
        "text": "2. Создайте новый DOM-элемент и добавьте его на страницу."
      },
      {
        "type": "p",
        "text": "3. Удалите элемент из DOM-дерева."
      },
      {
        "type": "heading",
        "text": "Средний уровень"
      },
      {
        "type": "p",
        "text": "1. Реализуйте функцию пакетного обновления DOM."
      },
      {
        "type": "p",
        "text": "2. Создайте динамический список с добавлением и удалением элементов."
      },
      {
        "type": "p",
        "text": "3. Реализуйте валидацию формы в реальном времени."
      },
      {
        "type": "heading",
        "text": "Хардкор"
      },
      {
        "type": "p",
        "text": "1. Создайте простой virtual DOM с диффингом."
      },
      {
        "type": "p",
        "text": "2. Реализуйте систему делегирования событий с поддержкой вложенных селекторов."
      },
      {
        "type": "p",
        "text": "3. Напишите компонент-рендерер с минимальным влиянием на рефлоу."
      },
      {
        "type": "heading",
        "text": "Итог"
      },
      {
        "type": "p",
        "text": "Размеры и прокрутка элементов — фундаментальная тема для работы с веб-страницами. Понимание основных концепций и лучших практик поможет создавать быстрые и интерактивные приложения. Всегда думайте о производительности при манипуляциях с DOM."
      }
    ]
  },
  {
    "slug": "razmery-i-prokrutka-okna-koordinaty",
    "track": "dom",
    "order": 9,
    "title": "Размеры и прокрутка окна, координаты",
    "summary": "Работать с размерами окна и координатами элементов.",
    "sourceTitle": "Урок 2.4. Размеры и прокрутка окна, координаты",
    "blocks": [
      {
        "type": "heading",
        "text": "Размеры и прокрутка окна, координаты"
      },
      {
        "type": "heading",
        "text": "Цель урока"
      },
      {
        "type": "p",
        "text": "Работать с размерами окна (innerWidth/Height) и координатами элементов (getBoundingClientRect, offsetX/Y)."
      },
      {
        "type": "heading",
        "text": "Теория"
      },
      {
        "type": "heading",
        "text": "Ментальная модель"
      },
      {
        "type": "p",
        "text": "Размеры и прокрутка окна, координаты — важная тема для понимания работы с DOM в браузере. Каждый элемент страницы — это объект со свойствами и методами, которые можно изучить и использовать для создания интерактивных веб-страниц."
      },
      {
        "type": "heading",
        "text": "Основные концепции"
      },
      {
        "type": "p",
        "text": "1. Структура: DOM — это дерево узлов, где каждый элемент имеет родителя и детей"
      },
      {
        "type": "p",
        "text": "2. События: Пользовательские действия генерируют события, которые можно перехватывать"
      },
      {
        "type": "p",
        "text": "3. Манипуляции: Создание, изменение и удаление элементов для динамического контента"
      },
      {
        "type": "p",
        "text": "4. Производительность: Правильная работа с DOM критична для быстродействия"
      },
      {
        "type": "heading",
        "text": "Примеры кода"
      },
      {
        "type": "heading",
        "text": "Базовый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "let element = document.querySelector(\".example\");\nconsole.log(element);"
      },
      {
        "type": "heading",
        "text": "Продвинутый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "class DOMHelper {\n  static createElement(tag, attrs, children) {\n    let el = document.createElement(tag);\n    if (attrs) {\n      Object.entries(attrs).forEach(function([k, v]) {\n        el.setAttribute(k, v);\n      });\n    }\n    if (children) {\n      children.forEach(function(child) { el.appendChild(child); });\n    }\n    return el;\n  }\n  \n  static removeElement(el) {\n    if (el && el.remove) el.remove();\n  }\n}"
      },
      {
        "type": "heading",
        "text": "Подводные камни"
      },
      {
        "type": "list",
        "items": [
          "Производительность DOM: Каждое изменение DOM вызывает перерисовку (reflow/repaint)",
          "Пакетные обновления: Используйте DocumentFragment для пакетной вставки",
          "Event listeners: Не забывайте снимать обработчики при удалении элементов",
          "CSSOM vs DOM: Стили и разметка — отдельные деревья при рендеринге",
          "requestAnimationFrame: Используйте для анимаций вместо setTimeout"
        ]
      },
      {
        "type": "heading",
        "text": "Практические задания"
      },
      {
        "type": "heading",
        "text": "Базовый уровень"
      },
      {
        "type": "p",
        "text": "1. Найдите элемент по CSS-селектору и измените его текст."
      },
      {
        "type": "p",
        "text": "2. Создайте новый DOM-элемент и добавьте его на страницу."
      },
      {
        "type": "p",
        "text": "3. Удалите элемент из DOM-дерева."
      },
      {
        "type": "heading",
        "text": "Средний уровень"
      },
      {
        "type": "p",
        "text": "1. Реализуйте функцию пакетного обновления DOM."
      },
      {
        "type": "p",
        "text": "2. Создайте динамический список с добавлением и удалением элементов."
      },
      {
        "type": "p",
        "text": "3. Реализуйте валидацию формы в реальном времени."
      },
      {
        "type": "heading",
        "text": "Хардкор"
      },
      {
        "type": "p",
        "text": "1. Создайте простой virtual DOM с диффингом."
      },
      {
        "type": "p",
        "text": "2. Реализуйте систему делегирования событий с поддержкой вложенных селекторов."
      },
      {
        "type": "p",
        "text": "3. Напишите компонент-рендерер с минимальным влиянием на рефлоу."
      },
      {
        "type": "heading",
        "text": "Итог"
      },
      {
        "type": "p",
        "text": "Размеры и прокрутка окна, координаты — фундаментальная тема для работы с веб-страницами. Понимание основных концепций и лучших практик поможет создавать быстрые и интерактивные приложения. Всегда думайте о производительности при манипуляциях с DOM."
      }
    ]
  },
  {
    "slug": "vspytye-i-pogruzhenie",
    "track": "dom",
    "order": 10,
    "title": "Всплытие и погружение",
    "summary": "Понять фазы всплытия и погружения событий.",
    "sourceTitle": "Урок 3.1. Всплытие и погружение",
    "blocks": [
      {
        "type": "heading",
        "text": "Всплытие и погружение"
      },
      {
        "type": "heading",
        "text": "Цель урока"
      },
      {
        "type": "p",
        "text": "Понять фазы всплытия (bubbling) и погружения (capturing) событий, и как их контролировать."
      },
      {
        "type": "heading",
        "text": "Теория"
      },
      {
        "type": "heading",
        "text": "Ментальная модель"
      },
      {
        "type": "p",
        "text": "Всплытие и погружение — важная тема для понимания работы с DOM в браузере. Каждый элемент страницы — это объект со свойствами и методами, которые можно изучить и использовать для создания интерактивных веб-страниц."
      },
      {
        "type": "heading",
        "text": "Основные концепции"
      },
      {
        "type": "p",
        "text": "1. Структура: DOM — это дерево узлов, где каждый элемент имеет родителя и детей"
      },
      {
        "type": "p",
        "text": "2. События: Пользовательские действия генерируют события, которые можно перехватывать"
      },
      {
        "type": "p",
        "text": "3. Манипуляции: Создание, изменение и удаление элементов для динамического контента"
      },
      {
        "type": "p",
        "text": "4. Производительность: Правильная работа с DOM критична для быстродействия"
      },
      {
        "type": "heading",
        "text": "Примеры кода"
      },
      {
        "type": "heading",
        "text": "Базовый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "let element = document.querySelector(\".example\");\nconsole.log(element);"
      },
      {
        "type": "heading",
        "text": "Продвинутый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "class DOMHelper {\n  static createElement(tag, attrs, children) {\n    let el = document.createElement(tag);\n    if (attrs) {\n      Object.entries(attrs).forEach(function([k, v]) {\n        el.setAttribute(k, v);\n      });\n    }\n    if (children) {\n      children.forEach(function(child) { el.appendChild(child); });\n    }\n    return el;\n  }\n  \n  static removeElement(el) {\n    if (el && el.remove) el.remove();\n  }\n}"
      },
      {
        "type": "heading",
        "text": "Подводные камни"
      },
      {
        "type": "list",
        "items": [
          "Производительность DOM: Каждое изменение DOM вызывает перерисовку (reflow/repaint)",
          "Пакетные обновления: Используйте DocumentFragment для пакетной вставки",
          "Event listeners: Не забывайте снимать обработчики при удалении элементов",
          "CSSOM vs DOM: Стили и разметка — отдельные деревья при рендеринге",
          "requestAnimationFrame: Используйте для анимаций вместо setTimeout"
        ]
      },
      {
        "type": "heading",
        "text": "Практические задания"
      },
      {
        "type": "heading",
        "text": "Базовый уровень"
      },
      {
        "type": "p",
        "text": "1. Найдите элемент по CSS-селектору и измените его текст."
      },
      {
        "type": "p",
        "text": "2. Создайте новый DOM-элемент и добавьте его на страницу."
      },
      {
        "type": "p",
        "text": "3. Удалите элемент из DOM-дерева."
      },
      {
        "type": "heading",
        "text": "Средний уровень"
      },
      {
        "type": "p",
        "text": "1. Реализуйте функцию пакетного обновления DOM."
      },
      {
        "type": "p",
        "text": "2. Создайте динамический список с добавлением и удалением элементов."
      },
      {
        "type": "p",
        "text": "3. Реализуйте валидацию формы в реальном времени."
      },
      {
        "type": "heading",
        "text": "Хардкор"
      },
      {
        "type": "p",
        "text": "1. Создайте простой virtual DOM с диффингом."
      },
      {
        "type": "p",
        "text": "2. Реализуйте систему делегирования событий с поддержкой вложенных селекторов."
      },
      {
        "type": "p",
        "text": "3. Напишите компонент-рендерер с минимальным влиянием на рефлоу."
      },
      {
        "type": "heading",
        "text": "Итог"
      },
      {
        "type": "p",
        "text": "Всплытие и погружение — фундаментальная тема для работы с веб-страницами. Понимание основных концепций и лучших практик поможет создавать быстрые и интерактивные приложения. Всегда думайте о производительности при манипуляциях с DOM."
      }
    ]
  },
  {
    "slug": "delegirovanie-sobytiy",
    "track": "dom",
    "order": 11,
    "title": "Делегирование событий",
    "summary": "Освоить паттерн делегирования событий.",
    "sourceTitle": "Урок 3.2. Делегирование событий",
    "blocks": [
      {
        "type": "heading",
        "text": "Делегирование событий"
      },
      {
        "type": "heading",
        "text": "Цель урока"
      },
      {
        "type": "p",
        "text": "Освоить паттерн делегирования: один обработчик на родителе вместо множества на дочерних элементах."
      },
      {
        "type": "heading",
        "text": "Теория"
      },
      {
        "type": "heading",
        "text": "Ментальная модель"
      },
      {
        "type": "p",
        "text": "Делегирование событий — важная тема для понимания работы с DOM в браузере. Каждый элемент страницы — это объект со свойствами и методами, которые можно изучить и использовать для создания интерактивных веб-страниц."
      },
      {
        "type": "heading",
        "text": "Основные концепции"
      },
      {
        "type": "p",
        "text": "1. Структура: DOM — это дерево узлов, где каждый элемент имеет родителя и детей"
      },
      {
        "type": "p",
        "text": "2. События: Пользовательские действия генерируют события, которые можно перехватывать"
      },
      {
        "type": "p",
        "text": "3. Манипуляции: Создание, изменение и удаление элементов для динамического контента"
      },
      {
        "type": "p",
        "text": "4. Производительность: Правильная работа с DOM критична для быстродействия"
      },
      {
        "type": "heading",
        "text": "Примеры кода"
      },
      {
        "type": "heading",
        "text": "Базовый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "let element = document.querySelector(\".example\");\nconsole.log(element);"
      },
      {
        "type": "heading",
        "text": "Продвинутый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "class DOMHelper {\n  static createElement(tag, attrs, children) {\n    let el = document.createElement(tag);\n    if (attrs) {\n      Object.entries(attrs).forEach(function([k, v]) {\n        el.setAttribute(k, v);\n      });\n    }\n    if (children) {\n      children.forEach(function(child) { el.appendChild(child); });\n    }\n    return el;\n  }\n  \n  static removeElement(el) {\n    if (el && el.remove) el.remove();\n  }\n}"
      },
      {
        "type": "heading",
        "text": "Подводные камни"
      },
      {
        "type": "list",
        "items": [
          "Производительность DOM: Каждое изменение DOM вызывает перерисовку (reflow/repaint)",
          "Пакетные обновления: Используйте DocumentFragment для пакетной вставки",
          "Event listeners: Не забывайте снимать обработчики при удалении элементов",
          "CSSOM vs DOM: Стили и разметка — отдельные деревья при рендеринге",
          "requestAnimationFrame: Используйте для анимаций вместо setTimeout"
        ]
      },
      {
        "type": "heading",
        "text": "Практические задания"
      },
      {
        "type": "heading",
        "text": "Базовый уровень"
      },
      {
        "type": "p",
        "text": "1. Найдите элемент по CSS-селектору и измените его текст."
      },
      {
        "type": "p",
        "text": "2. Создайте новый DOM-элемент и добавьте его на страницу."
      },
      {
        "type": "p",
        "text": "3. Удалите элемент из DOM-дерева."
      },
      {
        "type": "heading",
        "text": "Средний уровень"
      },
      {
        "type": "p",
        "text": "1. Реализуйте функцию пакетного обновления DOM."
      },
      {
        "type": "p",
        "text": "2. Создайте динамический список с добавлением и удалением элементов."
      },
      {
        "type": "p",
        "text": "3. Реализуйте валидацию формы в реальном времени."
      },
      {
        "type": "heading",
        "text": "Хардкор"
      },
      {
        "type": "p",
        "text": "1. Создайте простой virtual DOM с диффингом."
      },
      {
        "type": "p",
        "text": "2. Реализуйте систему делегирования событий с поддержкой вложенных селекторов."
      },
      {
        "type": "p",
        "text": "3. Напишите компонент-рендерер с минимальным влиянием на рефлоу."
      },
      {
        "type": "heading",
        "text": "Итог"
      },
      {
        "type": "p",
        "text": "Делегирование событий — фундаментальная тема для работы с веб-страницами. Понимание основных концепций и лучших практик поможет создавать быстрые и интерактивные приложения. Всегда думайте о производительности при манипуляциях с DOM."
      }
    ]
  },
  {
    "slug": "dejstviya-brauzera-po-umolchaniyu",
    "track": "dom",
    "order": 12,
    "title": "Действия браузера по умолчанию",
    "summary": "Понять default actions браузера и как их предотвращать.",
    "sourceTitle": "Урок 3.3. Действия браузера по умолчанию",
    "blocks": [
      {
        "type": "heading",
        "text": "Действия браузера по умолчанию"
      },
      {
        "type": "heading",
        "text": "Цель урока"
      },
      {
        "type": "p",
        "text": "Понять default actions браузера (переходы, отправка форм) и как их предотвращать через preventDefault."
      },
      {
        "type": "heading",
        "text": "Теория"
      },
      {
        "type": "heading",
        "text": "Ментальная модель"
      },
      {
        "type": "p",
        "text": "Действия браузера по умолчанию — важная тема для понимания работы с DOM в браузере. Каждый элемент страницы — это объект со свойствами и методами, которые можно изучить и использовать для создания интерактивных веб-страниц."
      },
      {
        "type": "heading",
        "text": "Основные концепции"
      },
      {
        "type": "p",
        "text": "1. Структура: DOM — это дерево узлов, где каждый элемент имеет родителя и детей"
      },
      {
        "type": "p",
        "text": "2. События: Пользовательские действия генерируют события, которые можно перехватывать"
      },
      {
        "type": "p",
        "text": "3. Манипуляции: Создание, изменение и удаление элементов для динамического контента"
      },
      {
        "type": "p",
        "text": "4. Производительность: Правильная работа с DOM критична для быстродействия"
      },
      {
        "type": "heading",
        "text": "Примеры кода"
      },
      {
        "type": "heading",
        "text": "Базовый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "let element = document.querySelector(\".example\");\nconsole.log(element);"
      },
      {
        "type": "heading",
        "text": "Продвинутый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "class DOMHelper {\n  static createElement(tag, attrs, children) {\n    let el = document.createElement(tag);\n    if (attrs) {\n      Object.entries(attrs).forEach(function([k, v]) {\n        el.setAttribute(k, v);\n      });\n    }\n    if (children) {\n      children.forEach(function(child) { el.appendChild(child); });\n    }\n    return el;\n  }\n  \n  static removeElement(el) {\n    if (el && el.remove) el.remove();\n  }\n}"
      },
      {
        "type": "heading",
        "text": "Подводные камни"
      },
      {
        "type": "list",
        "items": [
          "Производительность DOM: Каждое изменение DOM вызывает перерисовку (reflow/repaint)",
          "Пакетные обновления: Используйте DocumentFragment для пакетной вставки",
          "Event listeners: Не забывайте снимать обработчики при удалении элементов",
          "CSSOM vs DOM: Стили и разметка — отдельные деревья при рендеринге",
          "requestAnimationFrame: Используйте для анимаций вместо setTimeout"
        ]
      },
      {
        "type": "heading",
        "text": "Практические задания"
      },
      {
        "type": "heading",
        "text": "Базовый уровень"
      },
      {
        "type": "p",
        "text": "1. Найдите элемент по CSS-селектору и измените его текст."
      },
      {
        "type": "p",
        "text": "2. Создайте новый DOM-элемент и добавьте его на страницу."
      },
      {
        "type": "p",
        "text": "3. Удалите элемент из DOM-дерева."
      },
      {
        "type": "heading",
        "text": "Средний уровень"
      },
      {
        "type": "p",
        "text": "1. Реализуйте функцию пакетного обновления DOM."
      },
      {
        "type": "p",
        "text": "2. Создайте динамический список с добавлением и удалением элементов."
      },
      {
        "type": "p",
        "text": "3. Реализуйте валидацию формы в реальном времени."
      },
      {
        "type": "heading",
        "text": "Хардкор"
      },
      {
        "type": "p",
        "text": "1. Создайте простой virtual DOM с диффингом."
      },
      {
        "type": "p",
        "text": "2. Реализуйте систему делегирования событий с поддержкой вложенных селекторов."
      },
      {
        "type": "p",
        "text": "3. Напишите компонент-рендерер с минимальным влиянием на рефлоу."
      },
      {
        "type": "heading",
        "text": "Итог"
      },
      {
        "type": "p",
        "text": "Действия браузера по умолчанию — фундаментальная тема для работы с веб-страницами. Понимание основных концепций и лучших практик поможет создавать быстрые и интерактивные приложения. Всегда думайте о производительности при манипуляциях с DOM."
      }
    ]
  },
  {
    "slug": "generatsiya-polzovatelskih-sobytiy",
    "track": "dom",
    "order": 13,
    "title": "Генерация пользовательских событий",
    "summary": "Научиться создавать и диспетчеризовать свои события.",
    "sourceTitle": "Урок 3.4. Генерация пользовательских событий",
    "blocks": [
      {
        "type": "heading",
        "text": "Генерация пользовательских событий"
      },
      {
        "type": "heading",
        "text": "Цель урока"
      },
      {
        "type": "p",
        "text": "Научиться создавать и диспетчеризовать свои события через new CustomEvent и dispatchEvent."
      },
      {
        "type": "heading",
        "text": "Теория"
      },
      {
        "type": "heading",
        "text": "Ментальная модель"
      },
      {
        "type": "p",
        "text": "Генерация пользовательских событий — важная тема для понимания работы с DOM в браузере. Каждый элемент страницы — это объект со свойствами и методами, которые можно изучить и использовать для создания интерактивных веб-страниц."
      },
      {
        "type": "heading",
        "text": "Основные концепции"
      },
      {
        "type": "p",
        "text": "1. Структура: DOM — это дерево узлов, где каждый элемент имеет родителя и детей"
      },
      {
        "type": "p",
        "text": "2. События: Пользовательские действия генерируют события, которые можно перехватывать"
      },
      {
        "type": "p",
        "text": "3. Манипуляции: Создание, изменение и удаление элементов для динамического контента"
      },
      {
        "type": "p",
        "text": "4. Производительность: Правильная работа с DOM критична для быстродействия"
      },
      {
        "type": "heading",
        "text": "Примеры кода"
      },
      {
        "type": "heading",
        "text": "Базовый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "let element = document.querySelector(\".example\");\nconsole.log(element);"
      },
      {
        "type": "heading",
        "text": "Продвинутый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "class DOMHelper {\n  static createElement(tag, attrs, children) {\n    let el = document.createElement(tag);\n    if (attrs) {\n      Object.entries(attrs).forEach(function([k, v]) {\n        el.setAttribute(k, v);\n      });\n    }\n    if (children) {\n      children.forEach(function(child) { el.appendChild(child); });\n    }\n    return el;\n  }\n  \n  static removeElement(el) {\n    if (el && el.remove) el.remove();\n  }\n}"
      },
      {
        "type": "heading",
        "text": "Подводные камни"
      },
      {
        "type": "list",
        "items": [
          "Производительность DOM: Каждое изменение DOM вызывает перерисовку (reflow/repaint)",
          "Пакетные обновления: Используйте DocumentFragment для пакетной вставки",
          "Event listeners: Не забывайте снимать обработчики при удалении элементов",
          "CSSOM vs DOM: Стили и разметка — отдельные деревья при рендеринге",
          "requestAnimationFrame: Используйте для анимаций вместо setTimeout"
        ]
      },
      {
        "type": "heading",
        "text": "Практические задания"
      },
      {
        "type": "heading",
        "text": "Базовый уровень"
      },
      {
        "type": "p",
        "text": "1. Найдите элемент по CSS-селектору и измените его текст."
      },
      {
        "type": "p",
        "text": "2. Создайте новый DOM-элемент и добавьте его на страницу."
      },
      {
        "type": "p",
        "text": "3. Удалите элемент из DOM-дерева."
      },
      {
        "type": "heading",
        "text": "Средний уровень"
      },
      {
        "type": "p",
        "text": "1. Реализуйте функцию пакетного обновления DOM."
      },
      {
        "type": "p",
        "text": "2. Создайте динамический список с добавлением и удалением элементов."
      },
      {
        "type": "p",
        "text": "3. Реализуйте валидацию формы в реальном времени."
      },
      {
        "type": "heading",
        "text": "Хардкор"
      },
      {
        "type": "p",
        "text": "1. Создайте простой virtual DOM с диффингом."
      },
      {
        "type": "p",
        "text": "2. Реализуйте систему делегирования событий с поддержкой вложенных селекторов."
      },
      {
        "type": "p",
        "text": "3. Напишите компонент-рендерер с минимальным влиянием на рефлоу."
      },
      {
        "type": "heading",
        "text": "Итог"
      },
      {
        "type": "p",
        "text": "Генерация пользовательских событий — фундаментальная тема для работы с веб-страницами. Понимание основных концепций и лучших практик поможет создавать быстрые и интерактивные приложения. Всегда думайте о производительности при манипуляциях с DOM."
      }
    ]
  },
  {
    "slug": "sobytiya-myshi-dvizheniya-drag-drop",
    "track": "dom",
    "order": 14,
    "title": "События мыши, движения, drag'n'drop",
    "summary": "Работать с событиями мыши, отслеживать положение, drag'n'drop.",
    "sourceTitle": "Урок 3.5. События мыши, движения, drag'n'drop",
    "blocks": [
      {
        "type": "heading",
        "text": "События мыши, движения, drag'n'drop"
      },
      {
        "type": "heading",
        "text": "Цель урока"
      },
      {
        "type": "p",
        "text": "Работать с событиями мыши (click, mousemove), отслеживать положение и реализовывать drag'n'drop."
      },
      {
        "type": "heading",
        "text": "Теория"
      },
      {
        "type": "heading",
        "text": "Ментальная модель"
      },
      {
        "type": "p",
        "text": "События мыши, движения, drag'n'drop — важная тема для понимания работы с DOM в браузере. Каждый элемент страницы — это объект со свойствами и методами, которые можно изучить и использовать для создания интерактивных веб-страниц."
      },
      {
        "type": "heading",
        "text": "Основные концепции"
      },
      {
        "type": "p",
        "text": "1. Структура: DOM — это дерево узлов, где каждый элемент имеет родителя и детей"
      },
      {
        "type": "p",
        "text": "2. События: Пользовательские действия генерируют события, которые можно перехватывать"
      },
      {
        "type": "p",
        "text": "3. Манипуляции: Создание, изменение и удаление элементов для динамического контента"
      },
      {
        "type": "p",
        "text": "4. Производительность: Правильная работа с DOM критична для быстродействия"
      },
      {
        "type": "heading",
        "text": "Примеры кода"
      },
      {
        "type": "heading",
        "text": "Базовый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "let element = document.querySelector(\".example\");\nconsole.log(element);"
      },
      {
        "type": "heading",
        "text": "Продвинутый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "class DOMHelper {\n  static createElement(tag, attrs, children) {\n    let el = document.createElement(tag);\n    if (attrs) {\n      Object.entries(attrs).forEach(function([k, v]) {\n        el.setAttribute(k, v);\n      });\n    }\n    if (children) {\n      children.forEach(function(child) { el.appendChild(child); });\n    }\n    return el;\n  }\n  \n  static removeElement(el) {\n    if (el && el.remove) el.remove();\n  }\n}"
      },
      {
        "type": "heading",
        "text": "Подводные камни"
      },
      {
        "type": "list",
        "items": [
          "Производительность DOM: Каждое изменение DOM вызывает перерисовку (reflow/repaint)",
          "Пакетные обновления: Используйте DocumentFragment для пакетной вставки",
          "Event listeners: Не забывайте снимать обработчики при удалении элементов",
          "CSSOM vs DOM: Стили и разметка — отдельные деревья при рендеринге",
          "requestAnimationFrame: Используйте для анимаций вместо setTimeout"
        ]
      },
      {
        "type": "heading",
        "text": "Практические задания"
      },
      {
        "type": "heading",
        "text": "Базовый уровень"
      },
      {
        "type": "p",
        "text": "1. Найдите элемент по CSS-селектору и измените его текст."
      },
      {
        "type": "p",
        "text": "2. Создайте новый DOM-элемент и добавьте его на страницу."
      },
      {
        "type": "p",
        "text": "3. Удалите элемент из DOM-дерева."
      },
      {
        "type": "heading",
        "text": "Средний уровень"
      },
      {
        "type": "p",
        "text": "1. Реализуйте функцию пакетного обновления DOM."
      },
      {
        "type": "p",
        "text": "2. Создайте динамический список с добавлением и удалением элементов."
      },
      {
        "type": "p",
        "text": "3. Реализуйте валидацию формы в реальном времени."
      },
      {
        "type": "heading",
        "text": "Хардкор"
      },
      {
        "type": "p",
        "text": "1. Создайте простой virtual DOM с диффингом."
      },
      {
        "type": "p",
        "text": "2. Реализуйте систему делегирования событий с поддержкой вложенных селекторов."
      },
      {
        "type": "p",
        "text": "3. Напишите компонент-рендерер с минимальным влиянием на рефлоу."
      },
      {
        "type": "heading",
        "text": "Итог"
      },
      {
        "type": "p",
        "text": "События мыши, движения, drag'n'drop — фундаментальная тема для работы с веб-страницами. Понимание основных концепций и лучших практик поможет создавать быстрые и интерактивные приложения. Всегда думайте о производительности при манипуляциях с DOM."
      }
    ]
  },
  {
    "slug": "formy-svojstva-metody-sobytiya",
    "track": "dom",
    "order": 15,
    "title": "Формы: свойства, методы, события",
    "summary": "Работать с формами: элементы, значения, валидация, события.",
    "sourceTitle": "Урок 4.1. Формы: свойства, методы, события",
    "blocks": [
      {
        "type": "heading",
        "text": "Формы: свойства, методы, события"
      },
      {
        "type": "heading",
        "text": "Цель урока"
      },
      {
        "type": "p",
        "text": "Работать с формами: элементы, значения, валидация, события (focus, blur, change, input)."
      },
      {
        "type": "heading",
        "text": "Теория"
      },
      {
        "type": "heading",
        "text": "Ментальная модель"
      },
      {
        "type": "p",
        "text": "Формы: свойства, методы, события — важная тема для понимания работы с DOM в браузере. Каждый элемент страницы — это объект со свойствами и методами, которые можно изучить и использовать для создания интерактивных веб-страниц."
      },
      {
        "type": "heading",
        "text": "Основные концепции"
      },
      {
        "type": "p",
        "text": "1. Структура: DOM — это дерево узлов, где каждый элемент имеет родителя и детей"
      },
      {
        "type": "p",
        "text": "2. События: Пользовательские действия генерируют события, которые можно перехватывать"
      },
      {
        "type": "p",
        "text": "3. Манипуляции: Создание, изменение и удаление элементов для динамического контента"
      },
      {
        "type": "p",
        "text": "4. Производительность: Правильная работа с DOM критична для быстродействия"
      },
      {
        "type": "heading",
        "text": "Примеры кода"
      },
      {
        "type": "heading",
        "text": "Базовый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "let element = document.querySelector(\".example\");\nconsole.log(element);"
      },
      {
        "type": "heading",
        "text": "Продвинутый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "class DOMHelper {\n  static createElement(tag, attrs, children) {\n    let el = document.createElement(tag);\n    if (attrs) {\n      Object.entries(attrs).forEach(function([k, v]) {\n        el.setAttribute(k, v);\n      });\n    }\n    if (children) {\n      children.forEach(function(child) { el.appendChild(child); });\n    }\n    return el;\n  }\n  \n  static removeElement(el) {\n    if (el && el.remove) el.remove();\n  }\n}"
      },
      {
        "type": "heading",
        "text": "Подводные камни"
      },
      {
        "type": "list",
        "items": [
          "Производительность DOM: Каждое изменение DOM вызывает перерисовку (reflow/repaint)",
          "Пакетные обновления: Используйте DocumentFragment для пакетной вставки",
          "Event listeners: Не забывайте снимать обработчики при удалении элементов",
          "CSSOM vs DOM: Стили и разметка — отдельные деревья при рендеринге",
          "requestAnimationFrame: Используйте для анимаций вместо setTimeout"
        ]
      },
      {
        "type": "heading",
        "text": "Практические задания"
      },
      {
        "type": "heading",
        "text": "Базовый уровень"
      },
      {
        "type": "p",
        "text": "1. Найдите элемент по CSS-селектору и измените его текст."
      },
      {
        "type": "p",
        "text": "2. Создайте новый DOM-элемент и добавьте его на страницу."
      },
      {
        "type": "p",
        "text": "3. Удалите элемент из DOM-дерева."
      },
      {
        "type": "heading",
        "text": "Средний уровень"
      },
      {
        "type": "p",
        "text": "1. Реализуйте функцию пакетного обновления DOM."
      },
      {
        "type": "p",
        "text": "2. Создайте динамический список с добавлением и удалением элементов."
      },
      {
        "type": "p",
        "text": "3. Реализуйте валидацию формы в реальном времени."
      },
      {
        "type": "heading",
        "text": "Хардкор"
      },
      {
        "type": "p",
        "text": "1. Создайте простой virtual DOM с диффингом."
      },
      {
        "type": "p",
        "text": "2. Реализуйте систему делегирования событий с поддержкой вложенных селекторов."
      },
      {
        "type": "p",
        "text": "3. Напишите компонент-рендерер с минимальным влиянием на рефлоу."
      },
      {
        "type": "heading",
        "text": "Итог"
      },
      {
        "type": "p",
        "text": "Формы: свойства, методы, события — фундаментальная тема для работы с веб-страницами. Понимание основных концепций и лучших практик поможет создавать быстрые и интерактивные приложения. Всегда думайте о производительности при манипуляциях с DOM."
      }
    ]
  },
  {
    "slug": "otpravka-formy",
    "track": "dom",
    "order": 16,
    "title": "Отправка формы",
    "summary": "Понять mechanism отправки форм: submit event, FormData.",
    "sourceTitle": "Урок 4.2. Отправка формы",
    "blocks": [
      {
        "type": "heading",
        "text": "Отправка формы"
      },
      {
        "type": "heading",
        "text": "Цель урока"
      },
      {
        "type": "p",
        "text": "Понять mechanism отправки форм: submit event, FormData, валидация перед отправкой, SPA-подход."
      },
      {
        "type": "heading",
        "text": "Теория"
      },
      {
        "type": "heading",
        "text": "Ментальная модель"
      },
      {
        "type": "p",
        "text": "Отправка формы — важная тема для понимания работы с DOM в браузере. Каждый элемент страницы — это объект со свойствами и методами, которые можно изучить и использовать для создания интерактивных веб-страниц."
      },
      {
        "type": "heading",
        "text": "Основные концепции"
      },
      {
        "type": "p",
        "text": "1. Структура: DOM — это дерево узлов, где каждый элемент имеет родителя и детей"
      },
      {
        "type": "p",
        "text": "2. События: Пользовательские действия генерируют события, которые можно перехватывать"
      },
      {
        "type": "p",
        "text": "3. Манипуляции: Создание, изменение и удаление элементов для динамического контента"
      },
      {
        "type": "p",
        "text": "4. Производительность: Правильная работа с DOM критична для быстродействия"
      },
      {
        "type": "heading",
        "text": "Примеры кода"
      },
      {
        "type": "heading",
        "text": "Базовый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "let element = document.querySelector(\".example\");\nconsole.log(element);"
      },
      {
        "type": "heading",
        "text": "Продвинутый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "class DOMHelper {\n  static createElement(tag, attrs, children) {\n    let el = document.createElement(tag);\n    if (attrs) {\n      Object.entries(attrs).forEach(function([k, v]) {\n        el.setAttribute(k, v);\n      });\n    }\n    if (children) {\n      children.forEach(function(child) { el.appendChild(child); });\n    }\n    return el;\n  }\n  \n  static removeElement(el) {\n    if (el && el.remove) el.remove();\n  }\n}"
      },
      {
        "type": "heading",
        "text": "Подводные камни"
      },
      {
        "type": "list",
        "items": [
          "Производительность DOM: Каждое изменение DOM вызывает перерисовку (reflow/repaint)",
          "Пакетные обновления: Используйте DocumentFragment для пакетной вставки",
          "Event listeners: Не забывайте снимать обработчики при удалении элементов",
          "CSSOM vs DOM: Стили и разметка — отдельные деревья при рендеринге",
          "requestAnimationFrame: Используйте для анимаций вместо setTimeout"
        ]
      },
      {
        "type": "heading",
        "text": "Практические задания"
      },
      {
        "type": "heading",
        "text": "Базовый уровень"
      },
      {
        "type": "p",
        "text": "1. Найдите элемент по CSS-селектору и измените его текст."
      },
      {
        "type": "p",
        "text": "2. Создайте новый DOM-элемент и добавьте его на страницу."
      },
      {
        "type": "p",
        "text": "3. Удалите элемент из DOM-дерева."
      },
      {
        "type": "heading",
        "text": "Средний уровень"
      },
      {
        "type": "p",
        "text": "1. Реализуйте функцию пакетного обновления DOM."
      },
      {
        "type": "p",
        "text": "2. Создайте динамический список с добавлением и удалением элементов."
      },
      {
        "type": "p",
        "text": "3. Реализуйте валидацию формы в реальном времени."
      },
      {
        "type": "heading",
        "text": "Хардкор"
      },
      {
        "type": "p",
        "text": "1. Создайте простой virtual DOM с диффингом."
      },
      {
        "type": "p",
        "text": "2. Реализуйте систему делегирования событий с поддержкой вложенных селекторов."
      },
      {
        "type": "p",
        "text": "3. Напишите компонент-рендерер с минимальным влиянием на рефлоу."
      },
      {
        "type": "heading",
        "text": "Итог"
      },
      {
        "type": "p",
        "text": "Отправка формы — фундаментальная тема для работы с веб-страницами. Понимание основных концепций и лучших практик поможет создавать быстрые и интерактивные приложения. Всегда думайте о производительности при манипуляциях с DOM."
      }
    ]
  },
  {
    "slug": "sobytiya-klaviatury-keydown-keyup",
    "track": "dom",
    "order": 17,
    "title": "События клавиатуры (keydown, keyup)",
    "summary": "Обрабатывать нажатия клавиш и реализовывать шорткаты.",
    "sourceTitle": "Урок 4.3. События клавиатуры (keydown, keyup)",
    "blocks": [
      {
        "type": "heading",
        "text": "События клавиатуры (keydown, keyup)"
      },
      {
        "type": "heading",
        "text": "Цель урока"
      },
      {
        "type": "p",
        "text": "Обрабатывать нажатия клавиш: key, code, ctrlKey, shiftKey и реализовывать клавиатурные шорткаты."
      },
      {
        "type": "heading",
        "text": "Теория"
      },
      {
        "type": "heading",
        "text": "Ментальная модель"
      },
      {
        "type": "p",
        "text": "События клавиатуры (keydown, keyup) — важная тема для понимания работы с DOM в браузере. Каждый элемент страницы — это объект со свойствами и методами, которые можно изучить и использовать для создания интерактивных веб-страниц."
      },
      {
        "type": "heading",
        "text": "Основные концепции"
      },
      {
        "type": "p",
        "text": "1. Структура: DOM — это дерево узлов, где каждый элемент имеет родителя и детей"
      },
      {
        "type": "p",
        "text": "2. События: Пользовательские действия генерируют события, которые можно перехватывать"
      },
      {
        "type": "p",
        "text": "3. Манипуляции: Создание, изменение и удаление элементов для динамического контента"
      },
      {
        "type": "p",
        "text": "4. Производительность: Правильная работа с DOM критична для быстродействия"
      },
      {
        "type": "heading",
        "text": "Примеры кода"
      },
      {
        "type": "heading",
        "text": "Базовый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "let element = document.querySelector(\".example\");\nconsole.log(element);"
      },
      {
        "type": "heading",
        "text": "Продвинутый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "class DOMHelper {\n  static createElement(tag, attrs, children) {\n    let el = document.createElement(tag);\n    if (attrs) {\n      Object.entries(attrs).forEach(function([k, v]) {\n        el.setAttribute(k, v);\n      });\n    }\n    if (children) {\n      children.forEach(function(child) { el.appendChild(child); });\n    }\n    return el;\n  }\n  \n  static removeElement(el) {\n    if (el && el.remove) el.remove();\n  }\n}"
      },
      {
        "type": "heading",
        "text": "Подводные камни"
      },
      {
        "type": "list",
        "items": [
          "Производительность DOM: Каждое изменение DOM вызывает перерисовку (reflow/repaint)",
          "Пакетные обновления: Используйте DocumentFragment для пакетной вставки",
          "Event listeners: Не забывайте снимать обработчики при удалении элементов",
          "CSSOM vs DOM: Стили и разметка — отдельные деревья при рендеринге",
          "requestAnimationFrame: Используйте для анимаций вместо setTimeout"
        ]
      },
      {
        "type": "heading",
        "text": "Практические задания"
      },
      {
        "type": "heading",
        "text": "Базовый уровень"
      },
      {
        "type": "p",
        "text": "1. Найдите элемент по CSS-селектору и измените его текст."
      },
      {
        "type": "p",
        "text": "2. Создайте новый DOM-элемент и добавьте его на страницу."
      },
      {
        "type": "p",
        "text": "3. Удалите элемент из DOM-дерева."
      },
      {
        "type": "heading",
        "text": "Средний уровень"
      },
      {
        "type": "p",
        "text": "1. Реализуйте функцию пакетного обновления DOM."
      },
      {
        "type": "p",
        "text": "2. Создайте динамический список с добавлением и удалением элементов."
      },
      {
        "type": "p",
        "text": "3. Реализуйте валидацию формы в реальном времени."
      },
      {
        "type": "heading",
        "text": "Хардкор"
      },
      {
        "type": "p",
        "text": "1. Создайте простой virtual DOM с диффингом."
      },
      {
        "type": "p",
        "text": "2. Реализуйте систему делегирования событий с поддержкой вложенных селекторов."
      },
      {
        "type": "p",
        "text": "3. Напишите компонент-рендерер с минимальным влиянием на рефлоу."
      },
      {
        "type": "heading",
        "text": "Итог"
      },
      {
        "type": "p",
        "text": "События клавиатуры (keydown, keyup) — фундаментальная тема для работы с веб-страницами. Понимание основных концепций и лучших практик поможет создавать быстрые и интерактивные приложения. Всегда думайте о производительности при манипуляциях с DOM."
      }
    ]
  },
  {
    "slug": "zagruzka-dokumenta-domcontentloaded-load",
    "track": "dom",
    "order": 18,
    "title": "Загрузка документа (DOMContentLoaded, load)",
    "summary": "Разобрать жизненный цикл загрузки страницы.",
    "sourceTitle": "Урок 5.1. Загрузка документа (DOMContentLoaded, load)",
    "blocks": [
      {
        "type": "heading",
        "text": "Загрузка документа (DOMContentLoaded, load)"
      },
      {
        "type": "heading",
        "text": "Цель урока"
      },
      {
        "type": "p",
        "text": "Разобрать жизненный цикл загрузки страницы: DOMContentLoaded, load, async/defer в скриптах."
      },
      {
        "type": "heading",
        "text": "Теория"
      },
      {
        "type": "heading",
        "text": "Ментальная модель"
      },
      {
        "type": "p",
        "text": "Загрузка документа (DOMContentLoaded, load) — важная тема для понимания работы с DOM в браузере. Каждый элемент страницы — это объект со свойствами и методами, которые можно изучить и использовать для создания интерактивных веб-страниц."
      },
      {
        "type": "heading",
        "text": "Основные концепции"
      },
      {
        "type": "p",
        "text": "1. Структура: DOM — это дерево узлов, где каждый элемент имеет родителя и детей"
      },
      {
        "type": "p",
        "text": "2. События: Пользовательские действия генерируют события, которые можно перехватывать"
      },
      {
        "type": "p",
        "text": "3. Манипуляции: Создание, изменение и удаление элементов для динамического контента"
      },
      {
        "type": "p",
        "text": "4. Производительность: Правильная работа с DOM критична для быстродействия"
      },
      {
        "type": "heading",
        "text": "Примеры кода"
      },
      {
        "type": "heading",
        "text": "Базовый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "let element = document.querySelector(\".example\");\nconsole.log(element);"
      },
      {
        "type": "heading",
        "text": "Продвинутый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "class DOMHelper {\n  static createElement(tag, attrs, children) {\n    let el = document.createElement(tag);\n    if (attrs) {\n      Object.entries(attrs).forEach(function([k, v]) {\n        el.setAttribute(k, v);\n      });\n    }\n    if (children) {\n      children.forEach(function(child) { el.appendChild(child); });\n    }\n    return el;\n  }\n  \n  static removeElement(el) {\n    if (el && el.remove) el.remove();\n  }\n}"
      },
      {
        "type": "heading",
        "text": "Подводные камни"
      },
      {
        "type": "list",
        "items": [
          "Производительность DOM: Каждое изменение DOM вызывает перерисовку (reflow/repaint)",
          "Пакетные обновления: Используйте DocumentFragment для пакетной вставки",
          "Event listeners: Не забывайте снимать обработчики при удалении элементов",
          "CSSOM vs DOM: Стили и разметка — отдельные деревья при рендеринге",
          "requestAnimationFrame: Используйте для анимаций вместо setTimeout"
        ]
      },
      {
        "type": "heading",
        "text": "Практические задания"
      },
      {
        "type": "heading",
        "text": "Базовый уровень"
      },
      {
        "type": "p",
        "text": "1. Найдите элемент по CSS-селектору и измените его текст."
      },
      {
        "type": "p",
        "text": "2. Создайте новый DOM-элемент и добавьте его на страницу."
      },
      {
        "type": "p",
        "text": "3. Удалите элемент из DOM-дерева."
      },
      {
        "type": "heading",
        "text": "Средний уровень"
      },
      {
        "type": "p",
        "text": "1. Реализуйте функцию пакетного обновления DOM."
      },
      {
        "type": "p",
        "text": "2. Создайте динамический список с добавлением и удалением элементов."
      },
      {
        "type": "p",
        "text": "3. Реализуйте валидацию формы в реальном времени."
      },
      {
        "type": "heading",
        "text": "Хардкор"
      },
      {
        "type": "p",
        "text": "1. Создайте простой virtual DOM с диффингом."
      },
      {
        "type": "p",
        "text": "2. Реализуйте систему делегирования событий с поддержкой вложенных селекторов."
      },
      {
        "type": "p",
        "text": "3. Напишите компонент-рендерер с минимальным влиянием на рефлоу."
      },
      {
        "type": "heading",
        "text": "Итог"
      },
      {
        "type": "p",
        "text": "Загрузка документа (DOMContentLoaded, load) — фундаментальная тема для работы с веб-страницами. Понимание основных концепций и лучших практик поможет создавать быстрые и интерактивные приложения. Всегда думайте о производительности при манипуляциях с DOM."
      }
    ]
  },
  {
    "slug": "mutationobserver-selection-sobytiynyy-cikl",
    "track": "dom",
    "order": 19,
    "title": "MutationObserver, Selection, событийный цикл",
    "summary": "Использовать MutationObserver, Selection API, event loop.",
    "sourceTitle": "Урок 5.2. MutationObserver, Selection, событийный цикл",
    "blocks": [
      {
        "type": "heading",
        "text": "MutationObserver, Selection, событийный цикл"
      },
      {
        "type": "heading",
        "text": "Цель урока"
      },
      {
        "type": "p",
        "text": "Использовать MutationObserver для отслеживания изменений DOM, Selection API и глубокое понимание event loop."
      },
      {
        "type": "heading",
        "text": "Теория"
      },
      {
        "type": "heading",
        "text": "Ментальная модель"
      },
      {
        "type": "p",
        "text": "MutationObserver, Selection, событийный цикл — важная тема для понимания работы с DOM в браузере. Каждый элемент страницы — это объект со свойствами и методами, которые можно изучить и использовать для создания интерактивных веб-страниц."
      },
      {
        "type": "heading",
        "text": "Основные концепции"
      },
      {
        "type": "p",
        "text": "1. Структура: DOM — это дерево узлов, где каждый элемент имеет родителя и детей"
      },
      {
        "type": "p",
        "text": "2. События: Пользовательские действия генерируют события, которые можно перехватывать"
      },
      {
        "type": "p",
        "text": "3. Манипуляции: Создание, изменение и удаление элементов для динамического контента"
      },
      {
        "type": "p",
        "text": "4. Производительность: Правильная работа с DOM критична для быстродействия"
      },
      {
        "type": "heading",
        "text": "Примеры кода"
      },
      {
        "type": "heading",
        "text": "Базовый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "let element = document.querySelector(\".example\");\nconsole.log(element);"
      },
      {
        "type": "heading",
        "text": "Продвинутый пример"
      },
      {
        "type": "code",
        "lang": "javascript",
        "code": "class DOMHelper {\n  static createElement(tag, attrs, children) {\n    let el = document.createElement(tag);\n    if (attrs) {\n      Object.entries(attrs).forEach(function([k, v]) {\n        el.setAttribute(k, v);\n      });\n    }\n    if (children) {\n      children.forEach(function(child) { el.appendChild(child); });\n    }\n    return el;\n  }\n  \n  static removeElement(el) {\n    if (el && el.remove) el.remove();\n  }\n}"
      },
      {
        "type": "heading",
        "text": "Подводные камни"
      },
      {
        "type": "list",
        "items": [
          "Производительность DOM: Каждое изменение DOM вызывает перерисовку (reflow/repaint)",
          "Пакетные обновления: Используйте DocumentFragment для пакетной вставки",
          "Event listeners: Не забывайте снимать обработчики при удалении элементов",
          "CSSOM vs DOM: Стили и разметка — отдельные деревья при рендеринге",
          "requestAnimationFrame: Используйте для анимаций вместо setTimeout"
        ]
      },
      {
        "type": "heading",
        "text": "Практические задания"
      },
      {
        "type": "heading",
        "text": "Базовый уровень"
      },
      {
        "type": "p",
        "text": "1. Найдите элемент по CSS-селектору и измените его текст."
      },
      {
        "type": "p",
        "text": "2. Создайте новый DOM-элемент и добавьте его на страницу."
      },
      {
        "type": "p",
        "text": "3. Удалите элемент из DOM-дерева."
      },
      {
        "type": "heading",
        "text": "Средний уровень"
      },
      {
        "type": "p",
        "text": "1. Реализуйте функцию пакетного обновления DOM."
      },
      {
        "type": "p",
        "text": "2. Создайте динамический список с добавлением и удалением элементов."
      },
      {
        "type": "p",
        "text": "3. Реализуйте валидацию формы в реальном времени."
      },
      {
        "type": "heading",
        "text": "Хардкор"
      },
      {
        "type": "p",
        "text": "1. Создайте простой virtual DOM с диффингом."
      },
      {
        "type": "p",
        "text": "2. Реализуйте систему делегирования событий с поддержкой вложенных селекторов."
      },
      {
        "type": "p",
        "text": "3. Напишите компонент-рендерер с минимальным влиянием на рефлоу."
      },
      {
        "type": "heading",
        "text": "Итог"
      },
      {
        "type": "p",
        "text": "MutationObserver, Selection, событийный цикл — фундаментальная тема для работы с веб-страницами. Понимание основных концепций и лучших практик поможет создавать быстрые и интерактивные приложения. Всегда думайте о производительности при манипуляциях с DOM."
      }
    ]
  }
] as Lesson[];
